version: '3.8'

services:
  # KV Server 1
  kvserver1:
    build:
      context: .
      dockerfile: kvServer/Dockerfile
    ports:
      - "8000:8000"
    command: ["-a", "0.0.0.0", "-p", "8000"]
    networks:
      - kv-network

  # KV Server 2
  kvserver2:
    build:
      context: .
      dockerfile: kvServer/Dockerfile
    ports:
      - "8002:8002"
    command: ["-a", "0.0.0.0", "-p", "8002"]
    networks:
      - kv-network

  # KV Server 3
  kvserver3:
    build:
      context: .
      dockerfile: kvServer/Dockerfile
    ports:
      - "8003:8003"
    command: ["-a", "0.0.0.0", "-p", "8003"]
    networks:
      - kv-network

  # Data Generator (run once)
  gendata:
    build:
      context: .
      dockerfile: genData/Dockerfile
    volumes:
      - ./:/workspace
    command: ["-k", "genData/keyFile.txt", "-n", "1000", "-d", "5", "-l", "5", "-m", "5"]
    profiles:
      - tools

  # KV Client
  kvclient:
    build:
      context: .
      dockerfile: kvClient/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/workspace
    command: ["-s", "serverFile.txt", "-i", "dataToIndex.txt", "-k", "2"]
    depends_on:
      - kvserver1
      - kvserver2
      - kvserver3
    networks:
      - kv-network
    profiles:
      - client

networks:
  kv-network:
    driver: bridge